### ISSUE TITLE
Code Refactoring Helm charts in this repo

### ISSUE THREAD

**Issue by woojoong88** [onosproject/onos-helm-charts#29]
I think I can start a code refactoring for Helm charts in this repo. Looks like there are some hard-coded values and redundant codes.
Also, two or more Helm charts use different variable names defined in `values.yaml` file, even if they have same semantics/values. This situation causes that the value overriding is a bit dirty and even getting hard. 

Therefore, I will check each Helm chart and start code refactoring later OCP demo.

**Comment by SeanCondon** [comment]
all done i think?

**Comment by woojoong88** [comment]
Yup Let me close it. All is good to me.
