### ISSUE TITLE
no matches for kind "ConsensusStore"

### ISSUE THREAD

**Issue by sunyone** [onosproject/onos-helm-charts#708]
I'm trying to test micro-onos 

$ helm -n micro-onos install onos-umbrella onosproject/onos-umbrella
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "onos-consensus-store" namespace: "micro-onos" from "": no matches for kind "ConsensusStore" in version "consensus.atomix.io/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "onos-config" namespace: "micro-onos" from "": no matches for kind "StorageProfile" in version "atomix.io/v3beta3"
ensure CRDs are installed first, resource mapping not found for name: "onos-topo" namespace: "micro-onos" from "": no matches for kind "StorageProfile" in version "atomix.io/v3beta3"
ensure CRDs are installed first]

helm -n kube-system list
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
atomix-controller       kube-system     1               2023-01-12 15:28:31.892003309 +0800 CST deployed        atomix-controller-0.6.9         v0.6.2     
atomix-raft-storage     kube-system     1               2023-01-12 15:35:07.703844341 +0800 CST deployed        atomix-raft-storage-0.1.26      v0.9.20    
onos-operator           kube-system     1               2023-01-12 15:35:26.934048992 +0800 CST deployed        onos-operator-0.5.6             v0.5.2     

$ kubectl -n kube-system get pods | grep -i atomix
atomix-controller-5676d776d-nhmbw                 1/1     Running   0          17m
atomix-raft-storage-controller-85d445cb5d-4gvfs   1/1     Running   0          10m

$ kubectl -n kube-system get pods | grep -i onos
onos-operator-app-55997c5989-gnwj8                1/1     Running   0          10m
onos-operator-topo-7bcd58d88d-m9w6x               1/1     Running   0          10m

**Comment by SeanCondon** [comment]
`atomix-runtime` chart has now replaced the two charts `atomix-controller` and `atomix-raft`

`helm -n kube-system install atomix-runtime atomix/atomix-runtime`

If you are uninstalling the older ones you will also have to remove the old CRDs

**Comment by sunyone** [comment]
thanks

NAME: onos-umbrella
LAST DEPLOYED: Thu Jan 12 17:52:57 2023
NAMESPACE: micro-onos
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing onos-umbrella Helm chart.
