### ISSUE TITLE
Deploy ONOS on GCP

### ISSUE THREAD

**Issue by Andrea-Campanella** [onosproject/onos-helm-charts#8]
Test and provide additional/resources/fixes for deploying ONOS on GCP

**Comment by Andrea-Campanella** [comment]
A few resources that might prove useful. 
Overview and guides
https://mydeveloperplanet.com/2019/03/27/first-steps-with-gcp-kubernetes-engine/ ---> see point 5 
https://docs.bitnami.com/kubernetes/get-started-gke/ --> skip tiller and helm
http://docs.shippable.com/deploy/tutorial/deploy-to-gcp-gke-helm/ --- > do not create tiller and do not issue `helm init`
Manage a project
https://cloud.google.com/resource-manager/docs/creating-managing-projects --> we need a project to create a cluster.
Manage Organisation roles
https://cloud.google.com/resource-manager/docs/default-access-control
Google cloud create cluster
https://cloud.google.com/kubernetes-engine/docs/how-to/creating-a-cluster
gCloud CLI
https://cloud.google.com/sdk/gcloud/
gCloud SDK download 
https://cloud.google.com/sdk/downloads
gCloud initialize
https://cloud.google.com/sdk/docs/initializing

**Comment by Andrea-Campanella** [comment]
https://cloud.google.com/kubernetes-engine/docs/how-to/deleting-a-cluster to delete a cluster

**Comment by SeanCondon** [comment]
all done
